# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('texto', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(upload_to='duvida/%Y/%m/%d/')),
                ('audio', models.FileField(upload_to='duvida/%Y/%m/%d/')),
                ('video', models.FileField(upload_to='duvida/%Y/%m/%d/')),
                ('deslike', models.ManyToManyField(related_name='deslike', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Disciplina')),
                ('like', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.TextField(max_length=255)),
                ('professsor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
