# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_duvida_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='deslike',
            field=models.ManyToManyField(blank=True, null=True, related_name='deslike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
