# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20161110_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='professsor',
        ),
        migrations.AddField(
            model_name='duvida',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicao',
            name='professsores',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='duvida/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='deslike',
            field=models.ManyToManyField(blank=True, related_name='deslike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='duvida/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='duvida/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='descricao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
