# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20161110_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvida',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='duvida',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='duvida/audios/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='duvida/imagens/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='duvida/videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='professsores',
            field=models.ManyToManyField(blank=True, related_name='professsores', to=settings.AUTH_USER_MODEL),
        ),
    ]
