# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20161110_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='alunos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='admin',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
