# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 04:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161110_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 11, 4, 57, 35, 519401, tzinfo=utc)),
        ),
    ]
