# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20161111_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asssunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, max_length=1000)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='comentario/imagens/%Y/%m/%d/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='comentario/audios/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='comentario/videos/%Y/%m/%d/')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deslike', models.ManyToManyField(blank=True, related_name='deslike_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='duvida',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='deslike',
            field=models.ManyToManyField(blank=True, related_name='deslike_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='texto',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comentario',
            name='duvida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Duvida'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duvida',
            name='assuntos',
            field=models.ManyToManyField(blank=True, related_name='assuntos', to='core.Asssunto'),
        ),
    ]
